### ISSUE TITLE
[Feature request] Would it be possible to add the bookmark to a single file, html wiki ?

### ISSUE THREAD

**Issue by Telumire** [ylh/tiddlymarker#1]
Hello ! First of all thanks a lot for this addon, so far it's working great for me.

I have a lot of "standard" tiddlywikis, html files and I was wondering if it would be possible to push the bookmarks to these files ?
Maybe using a similar approach to timimy ?

Have a great day !

**Comment by ylh** [comment]
I originally had a concept for a mode that would identify the tab running the user's TW, then attempt to execute some JS to add the bookmark. Unfortunately, the tabs API didn't give me quite the power necessary to do that. The Timimi approach is theoretically possible, but that would require directly modifying a user's TW, which would be a very sensitive bit of code – I might find myself responsible for breakage. The download mode was the compromise I arrived at.
