### ISSUE TITLE
Add created field

### ISSUE THREAD

**Issue by amreus** [ylh/tiddlymarker#3]
Can the `created` field be added to the json with the current date-time?  I use tiddlymarker to save the .json files to disk and process them later. I could create it from the file time, but that can change in various scenarios. Thanks.

**Comment by ylh** [comment]
Luckily, this is doable with the tiddler format section in settings; try this:
```javascript
let o = {
	title: title,
	tags: tags,
	text: text,
	fields: {
		rawtitle: rawtitle,
		link: url,
		created: (d => {
			const pad = (w, i) => ("0".repeat(w) + i).slice(-w);
			return pad(4, d.getFullYear())
			     + pad(2, d.getMonth() + 1)
			     + pad(2, d.getDate())
			     + pad(2, d.getHours())
			     + pad(2, d.getMinutes())
			     + pad(2, d.getSeconds())
			     + pad(3, d.getMilliseconds());
		})(new Date())
	}
};

if (icon !== undefined) {
	o.fields.icon = icon.title;
}

return o;
```

**Comment by amreus** [comment]
Very cool, thank you. I used the *UTC version of these because otherwise they are local dates but would be interpreted as UTC dates by TiddlyWiki.
